### ISSUE TITLE
Python error when executing

### ISSUE THREAD

**Issue by lpgauth** [swolegoal/squid-dl#1]
Hi, I wanted to give squid-dl a try but I'm getting the following error:
```
squid-dl -T Brogramming.json
     ⣠⣾⢿⣿⣷⣦
   ⣀⣼⢟⡱⣆⡹⠹⣿⣇            ⢠⣶⣿⠿⣦⡀
  ⠈⠛⠛⠊⠉⠁  ⠹⣿⣧⡀         ⢠⣿⠏⠁⠝⢪⣻⡦
           ⠙⢻⣿⡄       ⣴⣿⠏
             ⣿⣷      ⢸⣿⠁
            ⢀⣽⣿⣿⣿⣿⣿⣶⣦⣼⠟
   ⣀⡀     ⢀⣴⣿⣿⣿⢿⣿⣿⣿⣿⣿⣿⣷⡀
⢀⣴⣿⡿⢿⣷⡄   ⣼⣿⣿⣿⣿ ⠈⠙⠻⣿⣿⣿⣿⣷
⣾⣿⠱⠉⠛⣿⣿⣄ ⣀⣿⣿⣿⣿⣿    ⣀⣽⣿⣿⣿  ⣠⣶⣿⣷⣦⡀
⠈⠁   ⠙⠿⠿⠛⠛⢻⣿⣿⣿⣿ ⣀⣴⣾⣿⣿⣿⣿⣿⣤⣾⣿⡿⠖⡯⢿⣷
          ⠈⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠉⠛⠛⠉   ⠹⠟
          ⢀⣴⡾⠟⠿⣿⣿⣿⣿⠿⢿⡍
         ⣀⣾⡟        ⠈⣿⣶⣤⣤⣄⡀
    ⣰⣾⣿⣿⣿⣿⠏          ⠈⠛⠛⢿⣿⣿⣦
    ⠛⠉⠉⠉⠉      _    _   ⠈⠻⣿⣿⣇_ _
 ___ __ _ _  _(_)__| |___ __| | |
(_-</ _` | || | / _` |___/ _` | |
/__/\__, |\_,_|_\__,_|   \__,_|_|
       |_|


[INFO]: Starting squid-dl...
[INFO]: saving videos to "Brogramming" directory
Traceback (most recent call last):
  File "/opt/homebrew/bin/squid-dl", line 4, in <module>
    __import__('pkg_resources').run_script('squid-dl==0.9', 'squid-dl')
  File "/opt/homebrew/lib/python3.9/site-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/homebrew/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1460, in run_script
    exec(script_code, namespace, namespace)
  File "/opt/homebrew/lib/python3.9/site-packages/squid_dl-0.9-py3.9.egg/EGG-INFO/scripts/squid-dl", line 31, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/squid_dl-0.9-py3.9.egg/squid_dl/__init__.py", line 7, in main
  File "/opt/homebrew/lib/python3.9/site-packages/squid_dl-0.9-py3.9.egg/squid_dl/downloader.py", line 468, in main
  File "/opt/homebrew/lib/python3.9/site-packages/squid_dl-0.9-py3.9.egg/squid_dl/downloader.py", line 307, in resume_preprocess
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 183, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'
```

I saw a few threads about a similar issues but I'm not a Python expert so I haven't dug to deep yet. Have you seen this before?

**Comment by hapaxant** [comment]
I get this error too, any fix?
